# Generated by Django 3.2.9 on 2021-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Records',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField()),
                ('last_checked', models.DateTimeField()),
                ('check_counts', models.IntegerField()),
            ],
        ),
    ]
