# Generated by Django 3.2.9 on 2021-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_interface', '0002_auto_20211128_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
